spring.application.name=02-gestion-cursos


#configuraciones de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/02_gestion_cursos
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#configuraciones de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#dialecto
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8081